import { Category, Product } from '@/types/inventory';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, name: 'Fish', created_at: new Date('2026-01-10').toISOString() },
  { id: 2, name: 'Electronic Product', created_at: new Date('2026-01-12').toISOString() },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    category_id: 1,
    name: 'Gold fish (গোল্ড ফিশ)',
    default_unit: 'Pair',
    cost_price: 120.00,
    selling_price: 200.00,
    current_stock: 25,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 2,
    category_id: 1,
    name: 'Barb (বার্ব)',
    default_unit: 'Pair',
    cost_price: 80.00,
    selling_price: 150.00,
    current_stock: 30,
    created_at: new Date('2026-02-02').toISOString(),
  },
  {
    id: 3,
    category_id: 1,
    name: 'Gorami (গৌরামি)',
    default_unit: 'Pair',
    cost_price: 100.00,
    selling_price: 180.00,
    current_stock: 3, // Low Stock < 5
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 4,
    category_id: 1,
    name: 'Koi karp (কই কার্প)',
    default_unit: 'Pair',
    cost_price: 150.00,
    selling_price: 250.00,
    current_stock: 15,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 5,
    category_id: 1,
    name: 'Komet (কমেট)',
    default_unit: 'Pair',
    cost_price: 90.00,
    selling_price: 160.00,
    current_stock: 18,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 6,
    category_id: 1,
    name: 'Tetra (টেট্রা)',
    default_unit: 'Pair',
    cost_price: 70.00,
    selling_price: 120.00,
    current_stock: 40,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 7,
    category_id: 1,
    name: 'Jebra (জেব্রা)',
    default_unit: 'Pair',
    cost_price: 60.00,
    selling_price: 100.00,
    current_stock: 50,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 8,
    category_id: 1,
    name: 'Renbo shark (রেইনবো শার্ক)',
    default_unit: 'Pair',
    cost_price: 130.00,
    selling_price: 220.00,
    current_stock: 4, // Low Stock < 5
    created_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 9,
    category_id: 1,
    name: 'Black moly (ব্ল্যাক মলি)',
    default_unit: 'Pair',
    cost_price: 50.00,
    selling_price: 90.00,
    current_stock: 35,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 10,
    category_id: 1,
    name: 'White Moly (হোয়াইট মলি)',
    default_unit: 'Pair',
    cost_price: 50.00,
    selling_price: 90.00,
    current_stock: 30,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 11,
    category_id: 1,
    name: 'Guppy (গাপ্পি)',
    default_unit: 'Pair',
    cost_price: 40.00,
    selling_price: 80.00,
    current_stock: 60,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 12,
    category_id: 1,
    name: 'Perrot (প্যারেট)',
    default_unit: 'Pair',
    cost_price: 350.00,
    selling_price: 600.00,
    current_stock: 8,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 13,
    category_id: 1,
    name: 'Angel (অ্যাঞ্জেল)',
    default_unit: 'Pair',
    cost_price: 110.00,
    selling_price: 200.00,
    current_stock: 22,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 14,
    category_id: 2,
    name: 'Submersible Filter (সামার্সিবল ফিল্টার)',
    default_unit: 'Piece',
    cost_price: 350.00,
    selling_price: 550.00,
    current_stock: 15,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 15,
    category_id: 2,
    name: 'LED Aquarium Light Strip (এলইডি লাইট)',
    default_unit: 'Piece',
    cost_price: 450.00,
    selling_price: 750.00,
    current_stock: 10,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 16,
    category_id: 2,
    name: 'Automatic Water Heater 100W (হিটার)',
    default_unit: 'Piece',
    cost_price: 400.00,
    selling_price: 650.00,
    current_stock: 2, // Low Stock < 5
    created_at: new Date('2026-02-16').toISOString(),
  },
  {
    id: 17,
    category_id: 2,
    name: 'Air Pump Dual Outlet (অক্সিজেন পাম্প)',
    default_unit: 'Piece',
    cost_price: 250.00,
    selling_price: 420.00,
    current_stock: 12,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 18,
    category_id: 2,
    name: 'Aquarium Wave Maker Pump (ওয়েভ মেকার)',
    default_unit: 'Piece',
    cost_price: 600.00,
    selling_price: 950.00,
    current_stock: 3, // Low Stock < 5
    created_at: new Date('2026-02-18').toISOString(),
  },
];
